import React, { useState } from 'react';
import { 
  X, 
  Upload, 
  CheckCircle2, 
  ShieldAlert, 
  Paperclip,
  Trash2
} from 'lucide-react';
import type { Ticket, UserRole, TicketType } from '../types';
import { getTicketPrefix } from '../types';

interface RaiseTicketModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmitTicket: (newTicket: Omit<Ticket, 'id' | 'createdAt'>) => void;
  currentUserRole: UserRole;
  currentUserName: string;
}

export const RaiseTicketModal: React.FC<RaiseTicketModalProps> = ({
  isOpen,
  onClose,
  onSubmitTicket,
  currentUserRole,
  currentUserName,
}) => {
  if (!isOpen) return null;

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [ticketType, setTicketType] = useState<TicketType>('INCIDENT');
  const [category, setCategory] = useState('Machine Breakdown');
  const [subcategory, setSubcategory] = useState('Curing Press Failure');
  const [priority, setPriority] = useState<'Low' | 'Medium' | 'High' | 'Critical'>('Medium');
  const [department, setDepartment] = useState('Plant Machinery & Maintenance');
  const [raiseTo, setRaiseTo] = useState('Vikramaditya Singh');
  const [location, setLocation] = useState('Bay B - Plant 1');
  const [machineNumber, setMachineNumber] = useState('MAC-PRESS-08');
  const [severity, setSeverity] = useState<'Low' | 'Medium' | 'High' | 'Critical'>('Medium');
  const [expectedDate, setExpectedDate] = useState('2026-08-08');
  const [files, setFiles] = useState<{ name: string; size: string; type: string }[]>([]);

  // Compute dynamic Ticket ID prefix (e.g., IM0608261, RL0408261, DP0408263, CR0408261)
  const prefix = getTicketPrefix(ticketType);
  const autoGeneratedId = `${prefix}060826${Math.floor(1 + Math.random() * 9)}`;

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const newFiles = Array.from(e.target.files).map(file => ({
        name: file.name,
        size: `${(file.size / 1024).toFixed(1)} KB`,
        type: file.type.includes('pdf') ? 'PDF' : file.type.includes('image') ? 'Image' : 'Excel'
      }));
      setFiles(prev => [...prev, ...newFiles]);
    }
  };

  const removeFile = (index: number) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    onSubmitTicket({
      ticketNumber: autoGeneratedId,
      title,
      description,
      ticketType,
      category,
      subcategory,
      priority,
      department,
      status: 'Pending Approval',
      severity,
      location,
      machineNumber,
      raisedBy: currentUserName,
      raisedByRole: currentUserRole,
      currentApprover: raiseTo,
      expectedCompletionDate: expectedDate,
      attachments: files.map((f, i) => ({
        id: i + 1,
        fileName: f.name,
        fileType: f.type as any,
        fileSizeKb: parseInt(f.size),
        uploadedAt: '2026-08-06 15:35',
        url: '#'
      }))
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-3xl max-h-[90vh] glass-modal rounded-3xl shadow-2xl border border-slate-200 dark:border-white/10 flex flex-col overflow-hidden text-xs">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 dark:border-white/10 flex items-center justify-between bg-slate-50/50 dark:bg-[#0c0f16]">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-[#ffd600]/20 text-[#ffd600]">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-black text-slate-900 dark:text-white font-outfit uppercase tracking-wider">Create New Ticket</h2>
              <p className="text-[11px] text-slate-500 dark:text-slate-400">Smart-JK Automated Ticket Entry</p>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <span className="px-3 py-1 rounded-lg bg-[#ffd600]/10 text-amber-600 dark:text-[#ffd600] font-mono font-bold border border-[#ffd600]/30 text-xs">
              ID: {autoGeneratedId}
            </span>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:bg-slate-200 dark:hover:bg-white/10 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4 overflow-y-auto flex-1">
          
          {/* Title & Ticket Type */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Ticket Title *</label>
              <input
                type="text"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Brief description of the issue"
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              />
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Ticket Type *</label>
              <select
                value={ticketType}
                onChange={(e) => setTicketType(e.target.value as TicketType)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none font-mono font-bold"
              >
                <option value="INCIDENT">INCIDENT (IM)</option>
                <option value="PROBLEM">PROBLEM (PR)</option>
                <option value="SERVICE_REQUEST">SERVICE REQUEST (SR)</option>
                <option value="CHANGE_REQUEST">CHANGE REQUEST (CR)</option>
                <option value="DEPLOYMENT">DEPLOYMENT (DP)</option>
                <option value="RELEASE">RELEASE (RL)</option>
              </select>
            </div>
          </div>

          {/* Description */}
          <div>
            <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Detailed Description *</label>
            <textarea
              required
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Detailed description of symptom, error code, or line impact..."
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
            />
          </div>

          {/* Priority, Severity, Department */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Priority *</label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as any)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              >
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
                <option value="Critical">Critical</option>
              </select>
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Severity *</label>
              <select
                value={severity}
                onChange={(e) => setSeverity(e.target.value as any)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              >
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
                <option value="Critical">Critical</option>
              </select>
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Category *</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              >
                <option value="Machine Breakdown">Machine Breakdown</option>
                <option value="Quality Defect">Quality Defect</option>
                <option value="IT Hardware/Software">IT Hardware/Software</option>
                <option value="Scheduled Maintenance">Scheduled Maintenance</option>
                <option value="Safety Hazard">Safety Hazard</option>
              </select>
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Subcategory</label>
              <input
                type="text"
                value={subcategory}
                onChange={(e) => setSubcategory(e.target.value)}
                placeholder="e.g. Curing Press Failure"
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              />
            </div>
          </div>

          {/* Machine Number, Location, Raise To, Expected Date */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Machine Asset #</label>
              <input
                type="text"
                value={machineNumber}
                onChange={(e) => setMachineNumber(e.target.value)}
                placeholder="e.g. CUR-PRESS-04"
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              />
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Location *</label>
              <input
                type="text"
                required
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder="e.g. Bay B - Line 3"
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              />
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Department *</label>
              <select
                value={department}
                onChange={(e) => setDepartment(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              >
                <option value="Tire Manufacturing & Production">Tire Manufacturing & Production</option>
                <option value="Plant Machinery & Maintenance">Plant Machinery & Maintenance</option>
                <option value="Quality Assurance & Testing">Quality Assurance & Testing</option>
                <option value="IT Infrastructure & Automation">IT Infrastructure & Automation</option>
                <option value="Logistics & Supply Chain">Logistics & Supply Chain</option>
                <option value="Environment, Health & Safety">Environment, Health & Safety</option>
              </select>
            </div>

            <div>
              <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Assign / Approver *</label>
              <select
                value={raiseTo}
                onChange={(e) => setRaiseTo(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
              >
                <option value="Vikramaditya Singh">Vikramaditya Singh (JKMANAGER)</option>
                <option value="Ananya Deshmukh">Ananya Deshmukh (SMARTADMIN)</option>
                <option value="Rajesh Sharma">Rajesh Sharma (ADMIN)</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Target Date</label>
            <input
              type="date"
              value={expectedDate}
              onChange={(e) => setExpectedDate(e.target.value)}
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 dark:bg-[#080a14] border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-medium focus:border-[#ffd600] focus:outline-none"
            />
          </div>

          {/* Attachments Zone */}
          <div>
            <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Attachments (PDF, PNG, JPG, ZIP - Max 10MB)</label>
            <div className="relative border-2 border-dashed border-slate-300 dark:border-white/10 hover:border-[#ffd600] rounded-2xl p-5 text-center bg-slate-50 dark:bg-[#080a14] transition-colors">
              <input
                type="file"
                multiple
                onChange={handleFileUpload}
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
              />
              <Upload className="w-6 h-6 text-[#ffd600] mx-auto mb-1" />
              <p className="text-xs font-bold text-slate-700 dark:text-slate-300">Click or drag & drop files</p>
            </div>

            {files.length > 0 && (
              <div className="mt-2 flex flex-wrap gap-2">
                {files.map((file, index) => (
                  <div key={index} className="flex items-center space-x-2 px-3 py-1 rounded-lg bg-[#ffd600]/10 border border-[#ffd600]/30 text-slate-800 dark:text-slate-200 text-xs">
                    <Paperclip className="w-3.5 h-3.5 text-[#ffd600]" />
                    <span>{file.name} ({file.size})</span>
                    <button type="button" onClick={() => removeFile(index)} className="text-red-400 hover:text-red-600">
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Actions */}
          <div className="pt-3 border-t border-slate-200 dark:border-white/10 flex items-center justify-end space-x-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2.5 rounded-xl border border-slate-300 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10 font-bold transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-6 py-2.5 rounded-xl bg-[#ffd600] text-slate-950 font-black shadow-lg shadow-[#ffd600]/20 transition-all active:scale-95 flex items-center space-x-2 cursor-pointer"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>Submit Ticket</span>
            </button>
          </div>

        </form>

      </div>
    </div>
  );
};
