import React, { useState, useMemo } from 'react';
import { Play, X } from 'lucide-react';
import type { Ticket, UserRole, TicketType } from '../types';
import { getTicketPrefix } from '../types';

interface RaiseTicketModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmitTicket: (newTicket: Omit<Ticket, 'id' | 'createdAt'>) => void;
  currentUserRole: UserRole;
  currentUserName: string;
}

const SUBCATEGORY_MAP: Record<string, string[]> = {
  Software: [
    'Application Bug',
    'Access Control & Permissions',
    'Performance & Speed Issue',
    'Database Sync Error',
    'UI / UX Defect',
    'API & Integration Failure'
  ],
  Hardware: [
    'Printer & Scanner Fault',
    'Display & Monitor Defect',
    'Workstation / Desktop Unit',
    'Barcode Scanner TC27 Fault',
    'Peripheral / Cable Damage'
  ],
  'Machine Breakdown': [
    'Curing Press Failure',
    'Hydraulic Line Pressure Drop',
    'Conveyor Belt Jam',
    'Motor Overheating',
    'PLC Controller Failure'
  ],
  'Quality Defect': [
    'Tire Tread Imperfection',
    'Sidewall Deformation',
    'Rubber Compound Imbalance',
    'Laser Inspection Rejection'
  ],
  'IT Infrastructure & Automation': [
    'Network Outage',
    'Server Connection Timeout',
    'Wi-Fi Access Point Offline',
    'Firewall / Port Block',
    'VPN Tunnel Drop'
  ],
  'Scheduled Maintenance': [
    'Preventive Inspection',
    'Sensor Calibration',
    'Safety System Test',
    'Lubrication & Oil Change'
  ],
  'Safety Hazard': [
    'Oil Spill / Chemical Leak',
    'Exposed Electrical Wiring',
    'Machine Guard Missing',
    'Ventilation Defect'
  ],
  Network: [
    'Switch Port Failure',
    'Router Configuration Error',
    'IP Conflict',
    'Bandwidth Congestion'
  ],
  Database: [
    'Query Execution Timeout',
    'Table Lock / Deadlock',
    'Database Disk Full',
    'Backup Restoration Failure'
  ]
};

export const RaiseTicketModal: React.FC<RaiseTicketModalProps> = ({
  isOpen,
  onClose,
  onSubmitTicket,
  currentUserRole,
  currentUserName,
}) => {
  if (!isOpen) return null;

  // Form States matching exact screenshot fields
  const [title, setTitle] = useState('');
  const [ticketType, setTicketType] = useState<TicketType>('INCIDENT');
  const [priority, setPriority] = useState<string>('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Software');
  const [subcategory, setSubcategory] = useState('');
  const [department, setDepartment] = useState('');
  const [assignTo, setAssignTo] = useState('Unassigned');
  const [files, setFiles] = useState<{ name: string; size: string; type: string }[]>([]);

  // Compute subcategories based on active Category
  const subcategoryOptions = useMemo(() => {
    return SUBCATEGORY_MAP[category] || [
      'General Request',
      'System Error',
      'Configuration Update',
      'Maintenance'
    ];
  }, [category]);

  const handleCategoryChange = (newCat: string) => {
    setCategory(newCat);
    setSubcategory('');
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const newFiles = Array.from(e.target.files).map(file => ({
        name: file.name,
        size: `${(file.size / 1024).toFixed(1)} KB`,
        type: file.type.includes('pdf') ? 'PDF' : file.type.includes('image') ? 'Image' : 'Document'
      }));
      setFiles(prev => [...prev, ...newFiles]);
    }
  };

  const handleClear = () => {
    setTitle('');
    setTicketType('INCIDENT');
    setPriority('');
    setDescription('');
    setCategory('Software');
    setSubcategory('');
    setDepartment('');
    setAssignTo('Unassigned');
    setFiles([]);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!title.trim()) {
      alert('Please enter a ticket title.');
      return;
    }
    if (!priority) {
      alert('Please select a priority level.');
      return;
    }
    if (!description.trim()) {
      alert('Please enter a detailed description.');
      return;
    }

    const prefix = getTicketPrefix(ticketType);
    const autoGeneratedId = `${prefix}060826${Math.floor(10 + Math.random() * 89)}`;

    onSubmitTicket({
      ticketNumber: autoGeneratedId,
      title,
      description,
      ticketType,
      category: category || 'Software',
      subcategory: subcategory || 'General',
      priority: (priority as any) || 'Medium',
      department: department || 'Plant Machinery & Maintenance',
      status: 'Pending Approval',
      severity: (priority as any) || 'Medium',
      location: 'Plant 1 - Bay B',
      raisedBy: currentUserName,
      raisedByRole: currentUserRole,
      assignedTo: assignTo !== 'Unassigned' ? assignTo : undefined,
      currentApprover: assignTo !== 'Unassigned' ? assignTo : 'Vikramaditya Singh',
      expectedCompletionDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
      attachments: files.map((f, i) => ({
        id: i + 1,
        fileName: f.name,
        fileType: f.type as any,
        fileSizeKb: parseInt(f.size) || 120,
        uploadedAt: new Date().toISOString().replace('T', ' ').substring(0, 16),
        url: '#'
      }))
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 md:p-6 bg-slate-950/85 backdrop-blur-sm animate-fadeIn">
      <div className="relative w-full max-w-3xl max-h-[92vh] bg-[#111625] border-2 border-[#ffd600] rounded-2xl shadow-[0_0_35px_rgba(255,214,0,0.15)] flex flex-col overflow-hidden text-xs text-white">
        
        {/* Close Button Header */}
        <div className="flex items-center justify-between px-6 pt-4 pb-2 bg-[#111625]">
          <div className="flex items-center space-x-2">
            <span className="w-2.5 h-2.5 rounded-full bg-[#ffd600] animate-pulse"></span>
            <h2 className="text-sm font-extrabold text-[#ffd600] tracking-wider uppercase">NEW TICKET CREATION</h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body - Matches layout in screenshot */}
        <form onSubmit={handleSubmit} className="px-6 pb-6 pt-2 space-y-4 overflow-y-auto flex-1 font-sans">
          
          {/* TITLE * & TICKET TYPE */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                TITLE <span className="text-[#ffd600]">*</span>
              </label>
              <input
                type="text"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Brief description of the issue"
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white placeholder-slate-500 font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                TICKET TYPE
              </label>
              <select
                value={ticketType}
                onChange={(e) => setTicketType(e.target.value as TicketType)}
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-bold uppercase focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
              >
                <option value="INCIDENT">INCIDENT</option>
                <option value="PROBLEM">PROBLEM</option>
                <option value="SERVICE_REQUEST">SERVICE REQUEST</option>
                <option value="CHANGE_REQUEST">CHANGE REQUEST</option>
                <option value="DEPLOYMENT">DEPLOYMENT</option>
                <option value="RELEASE">RELEASE</option>
              </select>
            </div>
          </div>

          {/* PRIORITY * */}
          <div>
            <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
              PRIORITY <span className="text-[#ffd600]">*</span>
            </label>
            <select
              required
              value={priority}
              onChange={(e) => setPriority(e.target.value)}
              className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
            >
              <option value="" disabled>Select priority</option>
              <option value="Low">Low</option>
              <option value="Medium">Medium</option>
              <option value="High">High</option>
              <option value="Critical">Critical</option>
            </select>
          </div>

          {/* DESCRIPTION * */}
          <div>
            <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
              DESCRIPTION <span className="text-[#ffd600]">*</span>
            </label>
            <textarea
              required
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Detailed description..."
              className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white placeholder-slate-500 font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none transition-all resize-y"
            />
          </div>

          {/* CATEGORY & SUBCATEGORY */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                CATEGORY
              </label>
              <select
                value={category}
                onChange={(e) => handleCategoryChange(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
              >
                <option value="Software">Software</option>
                <option value="Hardware">Hardware</option>
                <option value="Machine Breakdown">Machine Breakdown</option>
                <option value="Quality Defect">Quality Defect</option>
                <option value="IT Infrastructure & Automation">IT Infrastructure & Automation</option>
                <option value="Scheduled Maintenance">Scheduled Maintenance</option>
                <option value="Safety Hazard">Safety Hazard</option>
                <option value="Network">Network</option>
                <option value="Database">Database</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                SUBCATEGORY
              </label>
              <select
                value={subcategory}
                onChange={(e) => setSubcategory(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
              >
                <option value="">Select sub-category</option>
                {subcategoryOptions.map((sub, idx) => (
                  <option key={idx} value={sub}>{sub}</option>
                ))}
              </select>
            </div>
          </div>

          {/* DEPARTMENT & ASSIGN TO */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                DEPARTMENT
              </label>
              <select
                value={department}
                onChange={(e) => setDepartment(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
              >
                <option value="">Select department</option>
                <option value="Tire Manufacturing & Production">Tire Manufacturing & Production</option>
                <option value="Plant Machinery & Maintenance">Plant Machinery & Maintenance</option>
                <option value="Quality Assurance & Testing">Quality Assurance & Testing</option>
                <option value="IT Infrastructure & Automation">IT Infrastructure & Automation</option>
                <option value="Logistics & Supply Chain">Logistics & Supply Chain</option>
                <option value="Environment, Health & Safety">Environment, Health & Safety</option>
                <option value="HR & Administration">HR & Administration</option>
                <option value="Finance & Accounts">Finance & Accounts</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
                ASSIGN TO
              </label>
              <select
                value={assignTo}
                onChange={(e) => setAssignTo(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg bg-[#080c18] border border-slate-700/80 text-white font-medium focus:border-[#ffd600] focus:ring-1 focus:ring-[#ffd600] outline-none cursor-pointer"
              >
                <option value="Unassigned">Unassigned</option>
                <option value="Vikramaditya Singh">Vikramaditya Singh (JKMANAGER)</option>
                <option value="Ananya Deshmukh">Ananya Deshmukh (SMARTADMIN)</option>
                <option value="Rajesh Sharma">Rajesh Sharma (ADMIN)</option>
                <option value="Priya Patel">Priya Patel (RE USER)</option>
                <option value="Suresh Nair">Suresh Nair (SUPPORT)</option>
              </select>
            </div>
          </div>

          {/* ATTACHMENT */}
          <div>
            <label className="block text-[11px] font-extrabold uppercase tracking-wider text-slate-200 mb-1.5">
              ATTACHMENT
            </label>
            <div className="w-full px-3.5 py-2 rounded-lg bg-[#080c18] border border-slate-700/80 flex items-center gap-3">
              <input
                type="file"
                multiple
                onChange={handleFileUpload}
                className="text-xs text-slate-300 file:mr-3 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-slate-800 file:text-slate-200 hover:file:bg-slate-700 cursor-pointer"
              />
            </div>
            <p className="text-[11px] text-slate-400 font-medium mt-1">
              Supported: PDF, DOC, PNG, JPG, ZIP (Max 10MB each)
            </p>
            {files.length > 0 && (
              <div className="mt-2 flex flex-wrap gap-2">
                {files.map((file, i) => (
                  <span key={i} className="px-2.5 py-1 rounded bg-slate-800 text-slate-300 text-[11px] font-medium border border-slate-700">
                    📎 {file.name} ({file.size})
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* ACTION BUTTONS: CLEAR & SUBMIT TICKET */}
          <div className="pt-4 flex items-center justify-start space-x-3">
            <button
              type="button"
              onClick={handleClear}
              className="px-4 py-2.5 rounded-lg border border-[#ffd600]/40 text-[#ffd600] hover:bg-[#ffd600]/10 font-extrabold text-xs tracking-wider uppercase flex items-center space-x-1.5 transition-colors cursor-pointer"
            >
              <X className="w-4 h-4" />
              <span>CLEAR</span>
            </button>

            <button
              type="submit"
              className="px-6 py-2.5 rounded-lg bg-[#ffd600] hover:bg-[#ffe033] text-slate-950 font-black text-xs tracking-wider uppercase flex items-center space-x-2 shadow-lg shadow-[#ffd600]/20 transition-all active:scale-95 cursor-pointer"
            >
              <Play className="w-3.5 h-3.5 fill-slate-950 stroke-none" />
              <span>SUBMIT TICKET</span>
            </button>
          </div>

        </form>

      </div>
    </div>
  );
};
